sudo: false
language: java
jdk:
        - oraclejdk8
before_install:
install:
        - mvn install package
after_success:
        - mvn clean
cache:
        directories:
                - $HOME/.m2
                - BuildTools